# Generated by Django 3.0.8 on 2020-07-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text="Enter the book's natural language(e.g. English, French, Japanese etc.)", to='catalog.Language'),
        ),
    ]
